({
    block : 'page',
    title : 'Yeoman BEM',
    favicon : 'favicon.ico',
    head : [{ elem : 'meta', attrs : { name : 'viewport', content : 'width=device-width, initial-scale=1.0' }}],
    styles : [{ elem : 'css', url : 'assets/application.min.css' }],
    scripts : [{ elem : 'js', url : 'assets/application.min.js' }],
    content : [
        {
            elem : 'header',
            tag : 'header',
            content : [
                {
                    tag : 'h2', content : 'Hello, World! This page generated by Yeoman generator-bem.'
                }
            ]
        },
        {
            elem : 'content',
            tag : 'main',
            content : [
                {
                    tag : 'p',
                    content : 'Find this in service.pages/index/index.bemjson.js'
                }
            ]
        },
        {
            elem : 'footer',
            tag : 'footer',
            content : [
                'License: MIT'
            ]
        }
    ]
})
